platform :ios, '10.0'
use_frameworks!

#source 'https://github.com/CocoaPods/Specs.git'
#source 'git@github.ehealthinnovation.org:PHIT/CocoaPods.git'

target 'CCToolbox_Example' do
  pod 'CCToolbox', :path => '../'


#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '3.0'
#        end
#    end
#  end
end
